# 資料庫
# database
database:
  ip: "127.0.0.1"
  port: 3306
  database: "!! YOUR_DATABASE_NAME !!"
  user: "!! YOUR_USER_NAME !!"
  password: "!! YOUR_USER_PASSWORD !!"

# 快取能保留多少時間 (毫秒)
# How long can the cache be retained (milliseconds)
cache-vitality-time: 60000

# 創建資料表時允許加入分區支持
#   如果資料庫是使用 MariaDB 可以啟用此選項
# Partition support is allowed when creating data tables
#   If the database is MariaDB can enable
create-table-can-partition: true

# 單次上傳允許的最大行數量
# Maximum number of rows allowed in a single upload
maximum-row-allowed: 8

# 單次上傳允許的最大欄數量
# Maximum number of columns allowed in a single upload
maximum-column-allowed: 8

# 預設玩家能上傳最大的地圖數量
#   如果裁切 2:2 那會是 4 個而不是 1 個
# Default player can upload the maximum number of maps
#   If cut 2:2 it will be 4 instead of 1
default-player-limit: 400

# 網址訪問速度限制 (秒)
#   全部網址共享一個速率限制棄
#   避免遭受到大量上傳請求的駭客攻擊
#   未處理完畢卻關機, 會導致當前列隊全部消失
# URL access speed limit (second)
#   All url share a rate limit discard
#   Avoid hacker attacks from a large number of upload requests
#   Shutting down before processing is completed will cause all current queues to disappear
url-rate-limit: 4

# 指令創建地圖速率限制 (毫秒)
# Instruction to create a map rate limit (millisecond)
create-rate-limit: 2000

# 允許的網址來源清單
# List of allowed URL sources
allowed-url-source-list:
  - "https://i.imgur.com/"
  -

# 如果裁切只有 1:1 則會獲得的地圖物品標籤
# If the crop is only 1:1, will get the map item tag
item-single-tag: "{map:%mapview.id%}"
# 如果裁切大於 1:1 則會獲得的地圖物品標籤
# If the crop is greater than 1:1, will get the map item label
item-multiple-tag: "{display:{Lore:['{\"extra\":[{\"italic\":false,\"color\":\"white\",\"text\":\"%mapview.column%-%mapview.row%\"}],\"text\":\"\"}']},map:%mapview.id%}"