# 要應用此設定檔
# 重新命名成 config.yml 即可





# 資料庫
database:
  ip: "127.0.0.1"
  port: 3306
  database: "!! 你的資料庫名稱 !!"
  user: "!! 你的帳號 !!"
  password: "!! 你的密碼 !!"



# 快取能保留多少時間 (毫秒)
cache-vitality-time: 60000



# 創建資料表時允許加入分區支持
#   如果資料庫是使用 MariaDB 可以啟用此選項
create-table-can-partition: true



# 單次上傳允許的最大行數量
maximum-row-allowed: 8
# 單次上傳允許的最大欄數量
maximum-column-allowed: 8



# 預設玩家能上傳最大的地圖數量
#   如果裁切 2:2 那會是 4 個而不是 1 個
default-player-limit: 400



# 網址訪問速度限制 (秒)
#   全部網址共享一個速率限制棄
#   避免遭受到大量上傳請求的駭客攻擊
#   未處理完畢卻關機, 會導致當前列隊全部消失
url-rate-limit: 4
# 指令創建地圖速率限制 (毫秒)
create-rate-limit: 2000



# 允許的網址來源清單
allowed-url-source-list:
  - "https://i.imgur.com/"



languages:
  no_permission: "無此權限"
  missing_parameters: "缺少參數"
  reread_configuration_successfully: "已重新讀取設定"
  reread_configuration_error: "重新讀取設定時發生錯誤"
  unknown_parameter_type: "未知的參數類型"
  only_be_used_by_player: "只能以玩家身分執行此指令"
  parameter_not_url: "輸入的參數不是網址: "
  image_download_failed: "圖片下載失敗: "
  image_read_failed: "圖片讀取失敗: "
  database_error: "資料庫錯誤"
  created_successfully: "創建成功, 地圖編號: "
  not_filled_map_on_hand: "手上拿著的物品不是地圖"
  map_no_original_data: "此地圖沒有原始資料"
  parameter_not_number: "參數不是數字: "
  given: "已給予: "
  deleted: "已刪除: "
  map_data_not_exist: "地圖資料不存在: "
  not_set_any_redirect: "沒有設置任何的重定向"
  redirect_set_successfully: "重導向設置成功"
  redirect_delete_successfully: "重導向刪除成功"
  redirect_list: "重導向清單:\n   優先級: 權限 => 地圖編號"
  parameter_not_aspect_ratio: "參數不是長寬比: "
  map_cannot_copy: "此地圖不可複製"
  your_upload_has_reached_limit: "你的上傳數量已達到限制: "
  url_not_allowed: "不允許使用此網址"
  player_not_online_use_uuid: "此玩家沒有在線上, 使用 UUID"
  parameter_not_player_name_or_uuid: "參數不是 玩家名稱 或 UUID: "
  set_successfully_now_limit: "設置完畢, 當前的上傳限制: "
  now_limit: "上傳限制: "
  exceeding_allowed_size: "超出允許的尺寸: "
  creation_speed_too_fast: "創建的速度太快了, 等一下"
  can_not_get_this_map: "你無法獲取此地圖"
  can_not_delete_this_map: "你無法刪除此地圖"